version: '3.8'
services:
    wordpress:
        image: wordpress
        build: ./requirements/wordpress/
        depends_on :
            - mariadb
        ports: 
            - "8080:80"
        restart: always
    mariadb:
        image: mariadb
        build: ./requirements/mariadb/
        restart: always
