version: '3.8'
services:
    wordpress:
        image: wordpress
        build: 
            dockerfile: ./requirements/wordpress/Dockerfile
        depends_on :
            - mariadb
        ports: 
            - "9000"
        restart: always
    mariadb:
        image: mariadb
        build: 
            dockerfile: ./requirements/mariadb/Dockerfile
        ports: 
            - "3306"
        restart: always
