version: '3.8'

services:
	nginx:
		image: nginx
		ports: 
			- "443:443"
		volumes:
		restart: always

	wordpress:
		image: wordpress
		ports: 
			- "9000"
		volumes:
		restart: always


	mariadb:
		image: mariadb
		ports: 
			- "3306"
		volumes: db_data
		restart: always
		environment: .env

secrets:
	ssh_key:
		file: 

network:
	
