#!/usr/bin/expect

spawn mysql_secure_installation
expect "Set root password? [Y/n]\r"
send -- "n\r"
expect "Remove anonymous users? [Y/n]\r"
send -- "Y\r"
expect "Disallow root login remotely? [Y/n]\r"
send -- "Y\r"
expect "Remove test database and access to it? [Y/n]\r"
send -- "Y\r"
expect "Reload privilege tables now? [Y/n]\r"
send -- "Y\r"
expect "Remove anonymous users? [Y/n]\r"
send -- "Y\r"
